services:
  - type: web
    name: earnings-calendar
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_SUPABASE_URL
        value: https://rgibsterkohbrorzzflu.supabase.co
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
